### ISSUE TITLE
host.json' was not found and is not optional.

### ISSUE THREAD

**Issue by scubaracer** [aliencube/AzureFunctions.Extensions#28]
Hi, When i depoy the latest version of github, and deploy. 
I get host.json' was not found and is not optional. when calling the swaggerui function.

2019-04-18T05:26:34  Welcome, you are now connected to log-streaming service.
2019-04-18T05:26:45.424 [Info] Function started (Id=57518a20-87d2-4da6-a8dd-c388b379057d)
2019-04-18T05:26:45.924 [Error] Exception while executing function: RenderSwaggerUI. Microsoft.Extensions.Configuration.FileExtensions: The configuration file 'host.json' was not found and is not optional. The physical path is 'D:\local\Temporary ASP.NET Files\root\e359b4f0\f82c3575\assembly\dl3\67deff64\host.json'.
2019-04-18T05:26:46.033 [Error] Function completed (Failure, Id=57518a20-87d2-4da6-a8dd-c388b379057d, Duration=601ms)

**Comment by justinyoo** [comment]
@scubaracer Thanks for your comment!

As of the version [`1.5.1`](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.5.1) expects that the `host.json` physically exists, although it contains nothing. The default content of `host.json` is:

```
{
}
```

**Comment by justinyoo** [comment]
Let me figure out how to set this as an optional.

**Comment by andrebts** [comment]
I'm having the same issue when publishing to Azure on a V1 environment.

**Comment by rychlym** [comment]
(Today first time I have just meet with your great product - so might be a different issue)  I am using V1 environment ,  In debug -AzureFunctionTools cli  no problem but hosted in the azure loked  like try to search in different folder:

From exception log:
FileNotFoundException : The configuration file 'host.json' was not found and is not optional. The physical path is 'D:\local\Temporary ASP.NET Files\root\f4168be2\6cf60a80\assembly\dl3\dcd37d59\host.json'.
2019-06-07T18:13:44.320 [Error] Exception: corelationId: 1b260e5c-ff5f-4e06-96a0-4b3f566dd29e, stack:    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
....

contrarily to directory from console (but it might be a mistake -a directory substitution - week experiences)
![image](https://user-images.githubusercontent.com/11144487/59125961-1e52f980-8964-11e9-9bb1-86f056cc78dc.png)

**Comment by andrebts** [comment]
Hello @rychlym, I had the same issue on using Azure Functions V1 with AlienCube. To solve the issue I had to download the Aliencube project and add Aliencube.AzureFunctions.FunctionAppCommon and Aliencube.AzureFunctions.Extensions.OpenApi to my solution, referencing it instead of the nuget package. After this I changed Aliencube.AzureFunctions.Extensions.OpenApi -> Configurations -> OpenApiAppSettingsBase at line 23 to the following when publishing to production:

``` 
var host = new ConfigurationBuilder()
                           .SetBasePath("/home/site/wwwroot/")
                           .AddJsonFile("host.json")
                           .Build();
```

While using it on a dev environment just keep using the variable "basePath".

Hope you guys can solve it soon for Azure Functions V1.

**Comment by justinyoo** [comment]
@scubaracer @rychlym @andrebts This has been fixed with the version [1.5.3](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.5.3).

Would you please check this out on your side?

**Comment by ghost** [comment]
@justinyoo i got into the same problem. My challenge is that i have to stick to functions v1 due to a dependent third party SDK, and when i deploy to azure, i get the same host.json was not found and is not optional issue.

When i am looking at the latest code in 'dev', i am seeing the implementation has changed. So the commit 'https://github.com/aliencube/AzureFunctions.Extensions/commit/ee9e63d9a7f335028ab4b798f0348926c715a5cd' has kind of changed. Can you please confirm if the latest work still works with v1? or i need to make some modifications at my end

**Comment by nitinarote** [comment]
Any further updates on it. Does this get resolved or still issue is there. In my case its works locally fine but after deployment in Azure Function App not working.
Because i also getting same problem for Azure funtion V1.

Getting below error,
2023-02-08T06:05:33.653 [Info] Function started (Id=857162bb-ceb8-41c3-9c2d-2536eb95e073)
2023-02-08T06:05:33.669 [Info] SwaggerUI page was requested.
2023-02-08T06:05:33.669 [Error] Exception while executing function: RenderSwaggerUI. ReminderFunctionApp: The type initializer for 'SwaggerFunction.OpenAPINew.OpenApiHttpTrigger' threw an exception. Microsoft.Extensions.Configuration.FileExtensions: The configuration file 'host.json' was not found and is not optional. The physical path is 'C:\local\Temporary ASP.NET Files\root\ead32014\38e3c87a\assembly\dl3\7d928f2f\003ae705_813bd901\host.json'.
2023-02-08T06:05:33.684 [Error] Function completed (Failure, Id=857162bb-ceb8-41c3-9c2d-2536eb95e073, Duration=15ms)
